-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 20:16:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_escola` DEFAULT CHARACTER SET utf8 ;
USE `api_escola` ;

-- -----------------------------------------------------
-- Table `api_escola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`aluno` (
  `matricula` INT NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`responsaveis` (
  `id_responsaveis` INT NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`id_responsaveis`),
  INDEX `fk_responsaveis_aluno_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_responsaveis_aluno`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `api_escola`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`turmas` (
  `id_turma` INT NOT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turmas_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `api_escola`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`materias` (
  `id_materia` INT NOT NULL,
  `nome_materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`cargos` (
  `id_cargo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `cargos_id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_cargos1_idx` (`cargos_id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargos1`
    FOREIGN KEY (`cargos_id_cargo`)
    REFERENCES `api_escola`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`lista_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_escola`.`lista_materias` (
  `id_lista_materias` INT NOT NULL,
  `turmas_id_turma` INT NOT NULL,
  `materias_id_materia` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_lista_materias`),
  INDEX `fk_lista_materias_turmas1_idx` (`turmas_id_turma` ASC) VISIBLE,
  INDEX `fk_lista_materias_materias1_idx` (`materias_id_materia` ASC) VISIBLE,
  INDEX `fk_lista_materias_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_materias_turmas1`
    FOREIGN KEY (`turmas_id_turma`)
    REFERENCES `api_escola`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_materias_materias1`
    FOREIGN KEY (`materias_id_materia`)
    REFERENCES `api_escola`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_materias_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `api_escola`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
