-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 21:59:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api_escola` DEFAULT CHARACTER SET utf8 ;
USE `api_escola` ;

-- -----------------------------------------------------
-- Table `api_escola`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`sexo` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`turmas` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`turmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`aluno` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo_id` INT NOT NULL,
  `alunocol` VARCHAR(45) NULL,
  `turmas_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_aluno_sexo_idx` (`sexo_id` ASC) VISIBLE,
  INDEX `fk_aluno_turmas1_idx` (`turmas_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_sexo`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `api_escola`.`sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `api_escola`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`responsaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`responsaveis` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`responsaveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `aluno_matricula` INT NOT NULL,
  `sexo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_responsaveis_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  INDEX `fk_responsaveis_sexo1_idx` (`sexo_id` ASC) VISIBLE,
  CONSTRAINT `fk_responsaveis_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `api_escola`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsaveis_sexo1`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `api_escola`.`sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`materias` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`materias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`cargos` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dt_nascimento` VARCHAR(45) NOT NULL,
  `cargos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_cargos1_idx` (`cargos_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargos1`
    FOREIGN KEY (`cargos_id`)
    REFERENCES `api_escola`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api_escola`.`lista_materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_escola`.`lista_materias` ;

CREATE TABLE IF NOT EXISTS `api_escola`.`lista_materias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `materias_id` INT NOT NULL,
  `turmas_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lista_materias_materias1_idx` (`materias_id` ASC) VISIBLE,
  INDEX `fk_lista_materias_turmas1_idx` (`turmas_id` ASC) VISIBLE,
  INDEX `fk_lista_materias_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_materias_materias1`
    FOREIGN KEY (`materias_id`)
    REFERENCES `api_escola`.`materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_materias_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `api_escola`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_materias_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `api_escola`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `api_escola`.`cargos`
-- -----------------------------------------------------
START TRANSACTION;
USE `api_escola`;
INSERT INTO `api_escola`.`cargos` (`id`, `nome`) VALUES (1, 'Masculino');
INSERT INTO `api_escola`.`cargos` (`id`, `nome`) VALUES (2, 'Feminino');
INSERT INTO `api_escola`.`cargos` (`id`, `nome`) VALUES (3, 'Outro');

COMMIT;

